### ISSUE TITLE
[ Social Page ] - Unwanted alphabet

### ISSUE THREAD

**Issue by Vranjan7077** [dreyfus92/astro-portfolio#20]
Hi @dreyfus92 , 

- I was checking your website and found out that there is an unwanted alphabet added to the socials page. 
- I believe this was added while saving the changes.
- Small request can you please have a look at this minor :bug:
- Your site looks awesome.

![image](https://github.com/dreyfus92/astro-portfolio/assets/36437758/3d5a5dbe-a4da-440d-8e85-8f31cbfebb4a)

https://github.com/dreyfus92/astro-portfolio/blob/3c7ec19110244edf02b15de0b595dd95406ae38b/src/pages/socials.astro#L26

**Comment by dreyfus92** [comment]
Hello @Vranjan7077, thank you for spotting this. I will fix this shortly.

**Comment by dreyfus92** [comment]
Fixed on this commit  7af2588e62d247acbe708821c3966ddca0b304d3
